# Generated by Django 2.1.5 on 2019-02-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_author', models.CharField(max_length=10)),
                ('name_jp', models.CharField(max_length=10)),
                ('name_en', models.CharField(max_length=20)),
                ('date_birth', models.DateField()),
                ('date_death', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_work', models.CharField(max_length=10)),
                ('title_jp', models.CharField(max_length=50)),
                ('title_en', models.CharField(max_length=50)),
                ('id_author', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('id_work',),
            },
        ),
    ]
